# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
    - os: linux
      dist: trusty
      r: release
    - os: linux
      dist: trusty
      r: devel

after_success:
  - Rscript -e 'covr::codecov()'

